### ISSUE TITLE
归档页点击排序按钮报错的问题

### ISSUE THREAD

**Issue by Sakurapole** [valaxyjs/valaxy-theme-starter#12]
如下图：
![image](https://github.com/valaxyjs/valaxy-theme-starter/assets/35411164/0580e8da-8e37-4fdb-af84-b0c72c2db0d6)
![image](https://github.com/valaxyjs/valaxy-theme-starter/assets/35411164/5c069082-7f30-4ad3-993f-8a99f8a6a923)

原因：
代码中在进行数组逆序时，直接在原数组使用了reverse函数，导致原数组发生变化从而导致递归

修改：
在YunPostCollpase.vue这个文件中将
```
const sortedYears = computed(() => {
  const y = years.value
  const arr = y.sort((a, b) => b - a)
  return isDesc.value ? arr : arr.reverse()
})
```
修改为
```
const sortedYears = computed(() => {
  const y = years.value
  const arr = y.sort((a, b) => b - a)
  return isDesc.value ? arr : [...arr].reverse()
})
```

**Comment by YunYouJun** [comment]
感谢反馈，已修复。https://github.com/YunYouJun/valaxy/commit/7a4533e2211e0af5c8813ab4370a1d3fca2a4d1f
