### ISSUE TITLE
The release of The new structure and the release command have not been adjusted

### ISSUE THREAD

**Issue by hairyf** [valaxyjs/valaxy-theme-starter#3]
As the title says, the content of the  docs does not apply

docs should be adjusted

```sh
cd theme
npm run release
npm publish
```

or

Process these two mls in root package scripts

```json
"release": "cd theme && git add -A && bumpp",
"publish:ci": "npm -C theme publish",
```

**Comment by hairyf** [comment]
I'm not sure if `Actions` needs to be adjusted, but I think it should be the same

**Comment by YunYouJun** [comment]
Fixed by `pnpm -r publish --access public --no-git-checks`.
