### ISSUE TITLE
pnpm  warn: Issues with peer dependencies found

### ISSUE THREAD

**Issue by hairyf** [valaxyjs/valaxy-theme-starter#4]
![image](https://user-images.githubusercontent.com/49724027/178114072-aea94f7b-d0da-47c3-9498-064274c71dee.png)

`pnpm.peerDependencyRules` should be added in root package

```json
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "@types/markdown-it",
        "@algolia/client-search",
        "@types/react",
        "react",
        "react-dom"
      ]
    }
  }
```

**Comment by YunYouJun** [comment]
Do you want to create a PR for it?

**Comment by YunYouJun** [comment]
I separate it and add it to theme, so valaxy do not depend @docsearch.

Thanks for your feedback.
