### ISSUE TITLE
更新 `valaxy` 版本导致 `sass` 出现问题

### ISSUE THREAD

**Issue by hikariyo** [valaxyjs/valaxy-theme-starter#9]
将 `valaxy` 更新到 `0.14.28` 后，会出现 `sass` 报错。

![U}PSFTF7T2PU(RJ)UBKV QY](https://user-images.githubusercontent.com/61240774/233795013-fff7df8d-b05a-4f24-96f3-679ea8888fb0.jpg)

可以观察到给出报错 `EISDIR`，所以有解决方案：在 `markdown.scss` ·与 `css-vars.scss` 中将第一行的 `@use` 语句加上 `index.scss`。

```scss
@use "valaxy/client/styles/mixins/index.scss" /* ... */
```

按理来说 `index.scss` 应该被自动加载，我在本地跑了 `sass` 的 `1.60` (对应 `valaxy 0.14.25`) 与 `1.62` (对应 `valaxy 0.14.28`) 版本都没有出现问题，不知导致本仓库出现报错的具体原因。但无论如何，上述解决方案是可行的。

**Comment by YunYouJun** [comment]
你想要创建一个 PR，并添加 `index.scss` 来修复它吗？
